GSPEM\GSPEMBundle\Entity\Sitio:
    type: entity
    table: sitios
    repositoryClass: GSPEM\GSPEMBundle\Repository\SitioRepository
    id:
        id:
            type: integer
            id: true
            column: id
            generator:
                strategy: AUTO
    fields:
            lat:
                type: string
                column: latitud
            name:
                type: string
                column: name
            long:
                type: string
                column: longitud
            descript:
                type: string
                column: descript
            direccion:
                type: string
                column: direccion
            type:
                type: integer
                column: type
    lifecycleCallbacks: {  }
